# Generated by Django 4.2.20 on 2025-08-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_numb', models.CharField(max_length=10, unique=True)),
                ('race_name', models.CharField(max_length=100, unique=True)),
                ('race_order', models.IntegerField()),
                ('race_year', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_numb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.invoicenumber'),
        ),
    ]
