# Generated by Django 4.2.20 on 2025-08-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_match_invoice'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_invoice_be4f0a_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_numb',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice_numb',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice'], name='finance_tra_invoice_abceaa_idx'),
        ),
    ]
