# Generated by Django 4.2.20 on 2025-08-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummy', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'backup_base',
            },
        ),
        migrations.CreateModel(
            name='BackupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.backupbase',),
        ),
    ]
