# Generated by Django 4.2.20 on 2025-08-05 05:51

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_backupbase_backupproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=app.models.training_certificate_upload_path),
        ),
    ]
